# Generated by Django 6.0.7 on 2026-07-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('original_file_name', models.CharField(max_length=255)),
                ('s3_path', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='PENDING')),
            ],
        ),
    ]
