# Generated by Django 6.0.7 on 2026-07-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='s3_path',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
