# Generated by Django 6.0.7 on 2026-07-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_fileupload_file_name_alter_fileupload_s3_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PASSED', 'Passed'), ('REJECTED', 'Rejected'), ('ERROR', 'Error')], default='PENDING'),
        ),
    ]
