# Generated by Django 6.0.7 on 2026-07-21 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_alter_fileupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='scanned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='ScanCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_name', models.CharField(max_length=75)),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')])),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.fileupload')),
            ],
        ),
    ]
