# Generated by Django 6.0.7 on 2026-07-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_fileupload_scanned_at_scancheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scancheck',
            name='severity',
        ),
        migrations.AddField(
            model_name='scancheck',
            name='found_in_file',
            field=models.CharField(default='unknown', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scancheck',
            name='impact_severity',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNKNOWN', 'Unknown')], default='UNKNOWN'),
        ),
    ]
