# Generated by Django 6.0.7 on 2026-07-28 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_fileupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='project_name',
            field=models.CharField(max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scancheck',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='upload.fileupload'),
        ),
    ]
