services:
  api:
    build:
      context: ./api
    container_name: api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      # DEV ONLY (dummy creds)
      - GARAGE_ACCESS_KEY=local-dev-key
      - GARAGE_SECRET_KEY=4425f5c26c5e11581d3223904324dcb5b5d5dfb14e5e7f35e38c595424f5f1e6
      - GARAGE_ENDPOINT_URL=http://object-store:3900
      - GARAGE_DEFAULT_BUCKET=pending-bucket
      - PROCESSED_BUCKET=processed-bucket
      - INTERNAL_API_TOKEN=development-1234

  object-store:
    build:
      context: ./object-store
    container_name: object-store
    restart: unless-stopped
    ports:
      - "3900:3900" # S3 API
      - "3902:3902" # S3 Web
      - "3903:3903" # Admin API
    volumes:
      - ./object-store/garage.toml:/etc/garage.toml:ro
      - ./object-store/meta:/var/lib/garage/meta
      - ./object-store/data:/var/lib/garage/data
    environment:
      - GARAGE_CONFIG_FILE=/etc/garage.toml
      # DEV ONLY (dummy creds)
      - GARAGE_DEFAULT_ACCESS_KEY=local-dev-key
      - GARAGE_DEFAULT_SECRET_KEY=4425f5c26c5e11581d3223904324dcb5b5d5dfb14e5e7f35e38c595424f5f1e6
      - GARAGE_DEFAULT_BUCKET=pending-bucket
      - PROCESSED_BUCKET=processed-bucket

  rabbitmq:
    image: rabbitmq:4.3.0-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672" # management UI
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    restart: on-failure
    environment:
      - 'RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management path_prefix "/queue"'
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 4s
      timeout: 5s
      retries: 3
      start_period: 5s

  worker:
    build:
      context: ./worker
    deploy:
      replicas: 2
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      # DEV ONLY (dummy creds)
      - GARAGE_ACCESS_KEY=local-dev-key
      - GARAGE_SECRET_KEY=4425f5c26c5e11581d3223904324dcb5b5d5dfb14e5e7f35e38c595424f5f1e6
      - GARAGE_ENDPOINT_URL=http://object-store:3900
      - GARAGE_DEFAULT_BUCKET=pending-bucket
      - PROCESSED_BUCKET=processed-bucket
      - INTERNAL_API_TOKEN=development-1234
    develop:
      watch:
        - action: sync+restart
          path: ./worker
          target: /app
          ignore:
            - node_modules/
